name: CI/CD Pipeline


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Update to the latest version that supports Node.js 20
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build and Test
        run: |
          go build -o main .
          go test ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/botgauge-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/botgauge-app:latest

      - name: Deploy to EKS Cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EKS_HOST }}
          username: ${{ secrets.EKS_USERNAME }}
          key: ${{ secrets.EKS_PRIVATE_KEY }}
          script: |
            kubectl apply -f deployment.yaml
