name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to the latest version

      - name: Set up Go
        uses: actions/setup-go@v4  # Update to the latest version
        with:
          go-version: '1.18'  # Update to the desired Go version

      - name: Build the Go app
        run: go build -o main .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/botgauge-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/botgauge-app:latest
